### PR TITLE
setup.py for apertium python library

### PR DESCRIPTION
**Pull request by jamessandy**

### CODE REVIEW

**Comment by sushain97** [comment]
Thanks for the RR! This doesn't actually install Apertium itself which is the tricky part of this :)

**Comment by jamessandy** [comment]
Okay,thanks. will get back to work on it

**Comment by jamessandy** [comment]
if i am clear, am suppose to write a script to install apertium module ?

**Comment by sushain97** [comment]
There's an attempt to do that in this PR: https://github.com/apertium/apertium-python/pull/33. However, it needs to be cleaned up and integrated with the setup.py/pip workflow.

**Comment by jamessandy** [comment]
okay, i guess am to make the PR #33 installable in windows?

**Comment by sushain97** [comment]
That PR already does the install on Windows. It needs to be integrated into setup.py/pip. A user shouldn't have to run an extra script to finish the install. The script also needs to be cleaned up.

**Comment by jamessandy** [comment]
please where is the setup.py file ?

**Comment by jamessandy** [comment]
Hello @sushain97 am done with this, this is the link to the package https://pypi.org/manage/project/apertium-app/releases/  and you can install with >> pip install  apertium-app . Please need your review and comment.

**Comment by sushain97** [comment]
This doesn't handle any of the Windows installation steps. My comments above are unchanged.

**Comment by jamessandy** [comment]
please @sushain97 can you clear me up on this, i think am confused now

**Comment by sushain97** [comment]
I'm not sure where the confusion is coming from. This setup.py does not handle installation of Apertium itself. It only handles the installation of this API. Installing the API via setup.py should also install Apertium -- that is the entire purpose.

The setup.py file here is also missing a large number of important fields. See https://github.com/apertium/streamparser/blob/master/setup.py for a good example.

**Comment by jamessandy** [comment]
thanks, i think i know have an idea of what you're talking about, back to work

**Comment by jamessandy** [comment]
if i'm correct i'm expected to make apertium installable via windows command prompt?

**Comment by sushain97** [comment]
Not exactly. That's what the script in the other PR does. We want setup.py to run Python that installs Apertium.

**Comment by jamessandy** [comment]
Hello @sushain97 i am done with the new setup.py file for windows should i create a new pull request ?

**Comment by sushain97** [comment]
No, it should go here.

**Comment by jamessandy** [comment]
i should commit a change or just paste the code here ?

**Comment by sushain97** [comment]
Commit is preferable.

**Comment by jamessandy** [comment]
@sushain97 am done

**Comment by sushain97** [comment]
This does not install apertium core, it only installs the python package here.

**Comment by jamessandy** [comment]
i really don't understand anymore

**Comment by jamessandy** [comment]
you want a .exe file type for windows ?

**Comment by sushain97** [comment]
No. Have you looked at this PR: https://github.com/apertium/apertium-python/pull/33 ? Also, this wiki page: http://wiki.apertium.org/wiki/Installation.

**Comment by jamessandy** [comment]
Hello @sushain97 can I be pleased cleared, I'm to write a setup.py script to install Apertium from the Apertium repo on the coding challenge page. Is there something am doing wrong like the setup script or something am not doing. In my local machine I have built it and it's in an exe file for Windows and has a distro for Ubuntu and I have also put it up on pypi. Please clarify me so I can finish up😊😊 thanks and anticipating a rrpy soon

**Comment by sushain97** [comment]
This script only installs this Apertium Python library. It does not install Apertium itself.

**Comment by jamessandy** [comment]
@sushain97 is apertium itself contained in this repo ? https://github.com/apertium/apertium-python/

**Comment by sushain97** [comment]
No. It's contained in https://github.com/apertium/apertium. Did you look at my links above?

**Comment by jamessandy** [comment]
thanks sensei, just figured out where the issue is from..... back to work

**Comment by jamessandy** [comment]
@sushain97 i  have made changes

**Comment by sushain97** [comment]
Changing the URL in the `setup.py` doesn't do anything... That URL is just for documentation.

**Comment by jamessandy** [comment]
Then what exactly is the issue ?

**Comment by sushain97** [comment]
I've said the issue multiple times above. Have you read the links I've provided regarding the installation of Apertium itself? Apertium core itself is not a Python package, it's C++.

**Comment by jamessandy** [comment]
hello @sushain97 last question for now.. can i uses pipenv for this issue ?

**Comment by sushain97** [comment]
Sure. That shouldn't really be relevant here.

**Comment by jamessandy** [comment]
Ok. So what's your advice ?

**Comment by sushain97** [comment]
On what exactly?

**Pull request closed without merging**
