### PR TITLE
Improved docstrings

### PR DESCRIPTION
**Pull request by arghyatiger**

### CODE REVIEW

**Comment by sushain97** [comment]
This has a number of unrelated changes. Could you send a PR with just the doc changes so that I can review it properly? Also, I don't think dunder methods like __str__, __repr__ and __init__ need docstrings. I suggest using the docs from http://docs.python-requests.org/en/master/api/#main-interface as an example of how these ought to look.

**Comment by arghyatiger** [comment]
@sushain97  I understand, this must be pretty huge. I'll try to clean up the PR. :)

**Comment by arghyatiger** [comment]
@sushain97 The improved docstring commit was made by me on a version of the code from after improved repr, so, don't you think it's best if that gets merged first?
The order of changes are in order of the PRs made.

**Comment by sushain97** [comment]
> The improved docstring commit was made by me on a version of the code from after improved repr, so, don't you think it's best if that gets merged first?

Sure, but now that PR blocks this one and I can't really review it independently. Ideally, they would not depend on each other.

**Pull request closed without merging**
