### PR TITLE
Windows Script Isolated PR

### PR DESCRIPTION
**Pull request by arghyatiger**
The following has the ```windows.py``` script which when run should setup apertium+python to work from it's repo directory.

### CODE REVIEW

**Comment by sushain97** [comment]
Good to see a mostly isolated PR. I think there are still a number of unrelated changes that slipped in.

> to work from it's repo directory.

Installing from source is unfortunately not a great experience. This needs to be wrapped into the pip install script.

We also can't add a random dependency on `7z`. There aren't _any_ reputable Python libraries out there (packaged on pip) that can extract debian archives?

**Comment by sushain97** [comment]
Also, I think this PR should pass all checks since in theory it adds support for Windows on appveyor and doesn't break Linux support.

**Comment by arghyatiger** [comment]
I tried looking for one. Couldn't find any.
Also another interesting observation.
Appveyor seemed to have 7z run properly.

Strange, don't you think?

**Comment by arghyatiger** [comment]
@sushain,

There's an issue with apertium-all-dev right now according to Tino. The
binaries should work without any compilation once the lt-toolbox weights
feature is fixed.

**Comment by sushain97** [comment]
> I tried looking for one. Couldn't find any.

Have you tried https://packages.debian.org/sid/python-debian?

There's also http://unix-ar.readthedocs.io/en/latest/

that could be vendor'd if its license is compatible.

**Comment by arghyatiger** [comment]
@sushain97 

The packages aren't available for windows. I'm trying to look at other things that can be done.

**Comment by arghyatiger** [comment]
@sushain97  The appveyor build passes :)

**Comment by sushain97** [comment]
Awesome! Could you convert this to being in a `setup.py`'s install target? Then, both Linux and Windows should just run `python3 setup.py install` and then `test` without having to install any dependencies before hand. As far as the pair installation goes, that should be a separate command. Maybe something like `python3 -m apertium install eng` (we should at some point look into making this interface work for other options but that's another ticket). I'm OK with pushing removing the `7z` dependency to another ticket as well but as I've been saying, this interface should be all wrapped up in `setup.py`. Otherwise, users would have to clone the repo instead of using a normal Python installation method.

Finally, just asking users to set the PATH for each usage of the script is not sustainable. We need to modify the registry using something like what's described in `https://stackoverflow.com/questions/1085852/interface-for-modifying-windows-environment-variables-from-python` on install. I believe there's a way to get `pkg_resources` to provide you the absolute path where things get installed after `setup.py install` runs.

**Comment by arghyatiger** [comment]
@sushain97 ,  I wanted to make an initial script first to check if at all this method would work fine or not. So, now it's going to be a lot easier for me to write a ```setup.py```.

I've gone through the docs for the same and that's what I'll be doing now.

**Comment by arghyatiger** [comment]
@sushain97  making of the setup.py can be a good GCI task don't you think?

**Comment by sushain97** [comment]
This one is also on the list, a little broken up.

**Comment by arghyatiger** [comment]
@timkabot. 

Once apertium is set up on Windows the process and usage of lt-comp is pretty much the same.

The ```windows.py``` script should pretty much set up Apertium for you on your machine. 

Following which running Apertium lt-comp would be as trivial as it is on Linux/Mac OS

**Pull request closed without merging**
